# Generated by Django 4.1.3 on 2023-11-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="tracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.IntegerField()),
                ("state", models.IntegerField()),
                ("tracking_number", models.CharField(max_length=255)),
                ("date_creation", models.DateTimeField()),
                ("date_shipping", models.DateTimeField(null=True)),
                ("Shipping_Status", models.CharField(max_length=255)),
                ("Expected_Arrival", models.DateTimeField(null=True)),
                ("Arrival_Status", models.CharField(max_length=255)),
                ("history", models.JSONField()),
            ],
        ),
    ]
