# Generated by Django 4.2.7 on 2024-02-01 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shipping_tracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesorderitems",
            name="so",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="shipping_tracker.salesorders",
                verbose_name="SO",
            ),
        ),
    ]
