# Generated by Django 4.2.7 on 2024-01-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipping_tracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deviceattributes",
            name="model",
            field=models.CharField(max_length=40, verbose_name="Model"),
        ),
    ]
