# Generated by Django 4.2.7 on 2023-11-16 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shipping_tracker", "0002_remove_tracking_id_remove_tracking_state_and_more"),
    ]

    operations = [
        migrations.RenameModel(old_name="tracking", new_name="trackingDb",),
    ]
