# Generated by Django 4.2.7 on 2024-02-01 18:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shipping_tracker", "0002_alter_salesorderitems_so"),
    ]

    operations = [
        migrations.RenameField(
            model_name="salesorderitems",
            old_name="so",
            new_name="salesorder",
        ),
    ]
