# Generated by Django 4.2.7 on 2023-11-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipping_tracker", "0003_rename_tracking_trackingdb"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trackingdb",
            name="date_creation",
            field=models.DateField(null=True),
        ),
    ]
