# Generated by Django 4.2.7 on 2023-11-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipping_tracker", "0004_alter_trackingdb_date_creation"),
    ]

    operations = [
        migrations.AddField(
            model_name="trackingdb",
            name="ol_state",
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
