# Generated by Django 4.2.7 on 2024-01-31 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipping_tracker", "0004_address_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="country",
            field=models.CharField(max_length=20, verbose_name="Country"),
        ),
        migrations.DeleteModel(name="country",),
    ]
