# Generated by Django 4.2.7 on 2024-01-31 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shipping_tracker", "0005_alter_address_country_delete_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsalesorderitems",
            name="description",
            field=models.CharField(
                max_length=80, null=True, verbose_name="Description"
            ),
        ),
        migrations.AddField(
            model_name="salesorderitems",
            name="description",
            field=models.CharField(
                max_length=80, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="salesorderitems",
            name="sku",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="shipping_tracker.deviceattributes",
                verbose_name="SKU",
            ),
        ),
    ]
