# Generated by Django 4.2.7 on 2023-11-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipping_tracker", "0005_trackingdb_ol_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trackingdb",
            name="date_creation",
            field=models.DateTimeField(null=True),
        ),
    ]
