# Generated by Django 4.2.7 on 2024-01-31 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shipping_tracker", "0006_historicalsalesorderitems_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalsalesOrders",
            fields=[
                ("so", models.IntegerField(db_index=True, verbose_name="SO")),
                (
                    "date_created",
                    models.DateField(
                        blank=True, editable=False, verbose_name="Date Added"
                    ),
                ),
                (
                    "date_shipped",
                    models.DateField(null=True, verbose_name="Date Shipped"),
                ),
                (
                    "shipped_by",
                    models.CharField(
                        max_length=20, null=True, verbose_name="Shipped By"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        default="Open", max_length=20, null=True, verbose_name="State"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="shipping_tracker.customer",
                        verbose_name="Customer",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="shipping_tracker.warehouse",
                        verbose_name="Warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical sales orders",
                "verbose_name_plural": "historical sales orderss",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.DeleteModel(name="HistoricalsalesOrderItems",),
    ]
