# Generated by Django 4.2.7 on 2024-01-04 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shipping_tracker", "0007_alter_trackingdb_arrival_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="deviceAttributes",
            fields=[
                (
                    "sku",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="SKU"
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(max_length=20, verbose_name="Manufacturer"),
                ),
                ("model", models.CharField(max_length=20, verbose_name="Model")),
                ("color", models.CharField(max_length=20, verbose_name="Color")),
                ("capacity", models.CharField(max_length=20, verbose_name="Capacity")),
                (
                    "carrier",
                    models.CharField(blank=True, max_length=20, verbose_name="Carrier"),
                ),
                ("grade", models.CharField(max_length=20, verbose_name="Grade")),
            ],
        ),
        migrations.CreateModel(
            name="devices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imei", models.IntegerField(unique=True, verbose_name="IMEI")),
                ("status", models.CharField(max_length=20, verbose_name="Status")),
                (
                    "sku",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="shipping_tracker.deviceattributes",
                        verbose_name="SKU",
                    ),
                ),
            ],
        ),
    ]
