# Generated by Django 4.2.7 on 2024-01-15 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shipping_tracker", "0009_alter_deviceattributes_sku"),
    ]

    operations = [
        migrations.CreateModel(
            name="deviceStatus",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        default="Unvailable",
                        max_length=20,
                        verbose_name="Device Status",
                    ),
                ),
                (
                    "sellable",
                    models.BooleanField(default=False, verbose_name="Sellable"),
                ),
            ],
        ),
        migrations.RemoveField(model_name="devices", name="status",),
        migrations.AddField(
            model_name="devices",
            name="deviceStatus",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="shipping_tracker.devicestatus",
                verbose_name="Device Status",
            ),
        ),
    ]
