# Generated by Django 4.2.7 on 2024-01-15 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shipping_tracker", "0010_devicestatus_remove_devices_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devices",
            name="deviceStatus",
            field=models.ForeignKey(
                default=2,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="shipping_tracker.devicestatus",
                verbose_name="Device Status",
            ),
        ),
    ]
