# Generated by Django 4.2.7 on 2024-01-15 15:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("shipping_tracker", "0011_alter_devices_devicestatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="devices",
            name="battery",
            field=models.IntegerField(null=True, verbose_name="Battery"),
        ),
        migrations.AddField(
            model_name="devices",
            name="date_added",
            field=models.DateField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Date Added",
            ),
            preserve_default=False,
        ),
    ]
