# Generated by Django 4.2.7 on 2024-01-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shipping_tracker", "0013_currencies_warehouse_devices_date_tested_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpurchaseorders",
            name="po",
            field=models.CharField(max_length=20, verbose_name="PO"),
        ),
        migrations.AlterField(
            model_name="purchaseorders",
            name="po",
            field=models.CharField(max_length=20, verbose_name="PO"),
        ),
    ]
