# Generated by Django 4.2.7 on 2024-01-23 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shipping_tracker", "0014_alter_historicalpurchaseorders_po_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BackMarketListing",
            fields=[
                (
                    "listing_id",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("sku", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "min_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("backmarket_id", models.IntegerField()),
                ("product_id", models.UUIDField()),
                ("max_price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalBackMarketListing",
            fields=[
                ("listing_id", models.IntegerField(db_index=True)),
                ("sku", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "min_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("backmarket_id", models.IntegerField()),
                ("product_id", models.UUIDField()),
                ("max_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical back market listing",
                "verbose_name_plural": "historical back market listings",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
