# Generated by Django 4.2.7 on 2024-01-23 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shipping_tracker", "0015_backmarketlisting_historicalbackmarketlisting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="backmarketlisting",
            name="sku",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="shipping_tracker.deviceattributes",
                verbose_name="SKU",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbackmarketlisting",
            name="sku",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="shipping_tracker.deviceattributes",
                verbose_name="SKU",
            ),
        ),
    ]
