# Generated by Django 4.2.7 on 2024-01-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shipping_tracker", "0016_alter_backmarketlisting_sku_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="backmarketlisting",
            name="max_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="backmarketlisting",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="backmarketlisting",
            name="quantity",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalbackmarketlisting",
            name="max_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalbackmarketlisting",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalbackmarketlisting",
            name="quantity",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
