# Generated by Django 4.2.7 on 2024-01-24 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shipping_tracker", "0017_alter_backmarketlisting_max_price_and_more"),
    ]

    operations = [
        migrations.DeleteModel(name="HistoricalBackMarketListing",),
    ]
