# Generated by Django 4.2.7 on 2024-02-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deviceattributes",
            name="color",
            field=models.CharField(max_length=40, verbose_name="Color"),
        ),
    ]
