# Generated by Django 3.2.19 on 2024-02-07 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backmarketlisting',
            name='sku',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.deviceattributes', verbose_name='SKU'),
        ),
    ]
