# Generated by Django 4.2.7 on 2024-02-20 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_alter_deviceattributes_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="devices",
            name="sales_order_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="devices",
                to="inventory.salesorderitems",
                verbose_name="Sales Order Item",
            ),
        ),
        migrations.AddField(
            model_name="historicaldevices",
            name="sales_order_item",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="inventory.salesorderitems",
                verbose_name="Sales Order Item",
            ),
        ),
        migrations.AlterField(
            model_name="devices",
            name="so",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="devices",
                to="inventory.salesorders",
                verbose_name="SO",
            ),
        ),
    ]
