# Generated by Django 4.2.7 on 2024-02-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_alter_backmarketlisting_sku"),
    ]

    operations = [
        migrations.AddField(
            model_name="backmarketlisting",
            name="bm_sku",
            field=models.CharField(default="SKU", max_length=20, verbose_name="BM SKU"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalbackmarketlisting",
            name="bm_sku",
            field=models.CharField(default="SKU", max_length=20, verbose_name="BM SKU"),
            preserve_default=False,
        ),
    ]
