# Generated by Django 4.2.7 on 2024-02-21 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_devices_sales_order_item_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devices",
            name="so",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="devices",
                to="inventory.salesorders",
                verbose_name="SO",
            ),
        ),
    ]
