# Generated by Django 4.2.7 on 2024-02-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_alter_devices_so"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="street2",
            field=models.CharField(max_length=20, null=True, verbose_name="Street2"),
        ),
    ]
