# Generated by Django 4.2.7 on 2024-02-22 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_alter_address_street2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipment",
            name="so",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shipment",
                to="inventory.salesorders",
                verbose_name="SO",
            ),
        ),
    ]
