# Generated by Django 3.2.19 on 2024-02-08 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_auto_20240208_1352"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipment",
            name="shipping_label",
            field=models.URLField(
                max_length=500, null=True, verbose_name="Shipping Label"
            ),
        ),
    ]
