# Generated by Django 4.2.7 on 2024-02-28 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_alter_shipment_so"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="company",
            field=models.CharField(max_length=50, null=True, verbose_name="Company"),
        ),
        migrations.AlterField(
            model_name="backmarketlisting",
            name="sku",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="backmarket_listings",
                to="inventory.deviceattributes",
                verbose_name="SKU",
            ),
        ),
    ]
