# Generated by Django 3.2.19 on 2024-02-08 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_shipment_shipping_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='tracking_url',
            field=models.URLField(max_length=500, null=True, verbose_name='Tracking URL'),
        ),
    ]
