# Generated by Django 3.2.19 on 2024-02-09 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_backmarketlisting_bm_sku_and_more'),
        ('inventory', '0007_shipment_tracking_url'),
    ]

    operations = [
    ]
