# Generated by Django 4.2.7 on 2024-02-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_customer_company_alter_backmarketlisting_sku"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="city",
            field=models.CharField(max_length=40, verbose_name="City"),
        ),
        migrations.AlterField(
            model_name="address",
            name="state",
            field=models.CharField(max_length=40, verbose_name="State"),
        ),
        migrations.AlterField(
            model_name="address",
            name="street2",
            field=models.CharField(max_length=40, null=True, verbose_name="Street2"),
        ),
    ]
