# Generated by Django 3.2.19 on 2024-02-09 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_merge_20240209_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='shipping_label',
        ),
        migrations.AddField(
            model_name='shipment',
            name='label_blob_name',
            field=models.CharField(max_length=500, null=True, verbose_name='Shipping Label'),
        ),
    ]
