# Generated by Django 4.2.7 on 2024-02-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_alter_address_city_alter_address_state_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="contact",
            field=models.CharField(max_length=50, verbose_name="Contact"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Customer Name"),
        ),
    ]
