# Generated by Django 4.2.7 on 2024-03-04 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inventory", "0009_alter_customer_contact_alter_customer_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="RefurbedListing",
            fields=[
                (
                    "listing_id",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                (
                    "refurbed_sku",
                    models.CharField(max_length=100, verbose_name="Refurbed SKU"),
                ),
                ("title", models.CharField(max_length=255)),
                ("quantity", models.IntegerField(blank=True, null=True)),
                (
                    "ref_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "sku",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refurbed_listings",
                        to="inventory.deviceattributes",
                        verbose_name="SKU",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalRefurbedListing",
            fields=[
                ("listing_id", models.IntegerField(db_index=True)),
                (
                    "refurbed_sku",
                    models.CharField(max_length=100, verbose_name="Refurbed SKU"),
                ),
                ("title", models.CharField(max_length=255)),
                ("quantity", models.IntegerField(blank=True, null=True)),
                (
                    "ref_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sku",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="inventory.deviceattributes",
                        verbose_name="SKU",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical refurbed listing",
                "verbose_name_plural": "historical refurbed listings",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
