# Generated by Django 3.2.19 on 2024-02-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20240209_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='public_tacking_url',
            field=models.URLField(max_length=500, null=True, verbose_name='Public Tracking URL'),
        ),
    ]
