# Generated by Django 4.2.7 on 2024-02-15 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0011_rename_public_tacking_url_shipment_public_tracking_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="backmarketlisting",
            name="bm_sku",
            field=models.CharField(max_length=40, verbose_name="BM SKU"),
        ),
        migrations.AlterField(
            model_name="historicalbackmarketlisting",
            name="bm_sku",
            field=models.CharField(max_length=40, verbose_name="BM SKU"),
        ),
    ]
