# Generated by Django 4.2.7 on 2024-03-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0011_appconfig"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.CharField(max_length=120, verbose_name="Email"),
        ),
    ]
