# Generated by Django 4.2.7 on 2024-02-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0012_alter_backmarketlisting_bm_sku_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="backmarketlisting",
            name="bm_sku",
            field=models.CharField(max_length=100, verbose_name="BM SKU"),
        ),
        migrations.AlterField(
            model_name="historicalbackmarketlisting",
            name="bm_sku",
            field=models.CharField(max_length=100, verbose_name="BM SKU"),
        ),
    ]
