# Generated by Django 4.2.7 on 2024-03-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0012_alter_customer_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="street",
            field=models.CharField(max_length=120, verbose_name="Street"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="company",
            field=models.CharField(max_length=120, null=True, verbose_name="Company"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="contact",
            field=models.CharField(max_length=120, verbose_name="Contact"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="name",
            field=models.CharField(max_length=120, verbose_name="Customer Name"),
        ),
    ]
