# Generated by Django 4.2.7 on 2024-03-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0013_alter_address_street_alter_customer_company_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="city",
            field=models.CharField(max_length=50, verbose_name="City"),
        ),
        migrations.AlterField(
            model_name="address",
            name="name",
            field=models.CharField(max_length=120, verbose_name="Name"),
        ),
    ]
