# Generated by Django 4.2.7 on 2024-03-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0014_alter_address_city_alter_address_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="street2",
            field=models.CharField(max_length=120, null=True, verbose_name="Street2"),
        ),
    ]
