# Generated by Django 4.2.7 on 2024-03-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0015_alter_address_street2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesorderitems",
            name="unit_cost",
            field=models.DecimalField(
                decimal_places=2, max_digits=7, verbose_name="Unit Cost"
            ),
        ),
    ]
