runtime: python39

entrypoint: gunicorn -b :$PORT tracker_project.wsgi  

handlers:
- url: /static
  static_dir: static/

- url: /.*
  script: auto

env_variables:
  DJANGO_SETTINGS_MODULE: "tracker_project.cloud_settings"
  BUCKET_NAME: "inv-project-bucket"

